### PR TITLE
Update pongo2 from v4 to v6.

### PR DESCRIPTION
**Pull request by iredmail**
- [x] Update pongo2 from v4 to v6.
- [x] Drop Go v1.17 since pongo2 v6 requires Go v1.18.

### CODE REVIEW

**Comment by ReneWerner87** [comment]
will check it on sunday at the latest

**Comment by ReneWerner87** [comment]
maybe we should make it version 3 when it is no longer downward compatible due to the golang version change

**Comment by iredmail** [comment]
@ReneWerner87 Tagged v3. :)

**Comment by ReneWerner87** [comment]
thx, i will first create the tag for the old django v2 version(because of the new multi release strategy) and then we can merge it and create a new one

**Review by ReneWerner87 — APPROVED** [review]

**Pull request merged**
