### PR TITLE
fix bug for Network file system

### PR DESCRIPTION
**Pull request by mingkyme**
I fixed some bug for network file system.

It help to using embed library with import inner amber files.
```amber
doctype
html
    head
    body
        import components/header
        h1 Hi
        h2 Hi Hi
        import components/footer
```
for example
visit https://github.com/mingkyme/golang-embed-amber

### CODE REVIEW

**Comment by ReneWerner87** [comment]
Please provide a unittests for this fix

**Comment by mingkyme** [comment]
@ReneWerner87 I added test module.

**Review by ReneWerner87 — APPROVED** [review]

**Comment by mingkyme** [comment]
For keeping go version to 1.13 (following on README.md)
Have to remove "embed" module.

**Comment by ReneWerner87** [comment]
> For keeping go version to 1.13 (following on README.md) Have to remove "embed" module.

ok thats fine for me

**Comment by ReneWerner87** [comment]
@mingkyme can you do the last changes ?

**Comment by mingkyme** [comment]
@ReneWerner87 I removed test codes for keeping go version.

**Comment by ReneWerner87** [comment]
thx

https://github.com/valyala/fasthttp/blob/7a5afddf5b805a022f8e81281c772c11600da2f4/client_timing_wait_test.go#L1-L2
@mingkyme can you try one more thing for me ? move those tests you removed to a separate file and create this comment header above with the minimum version 

think then they will be skipped in the old versions and we still have tests for the new embed feature

**Comment by mingkyme** [comment]
I did.

**Pull request merged**
