### PR TITLE
Added html engine benchmark

### PR DESCRIPTION
**Pull request by ytsruh**
Adding benchmarks for issue #227 .

@ReneWerner87  could you take a look at this and let me know if you're happy with it before i do the other engines please?

### CODE REVIEW

**Comment by ReneWerner87** [comment]
maybe like this
https://github.com/gofiber/template/pull/230/commits/933cb10042f946eb0ddc4660654e22f39e6356f8

2 kind of benchmarks
and always the same input, output and functionality in/for the templates

**Comment by ReneWerner87** [comment]
@ytsruh

**Comment by ytsruh** [comment]
Brilliant thanks. Will work through the rest of the engines ASAP

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
@ytsruh thanks for the contribution

**Pull request merged**
