### PR TITLE
[jet] raise error occured in embed()

### LINKED ISSUE #341: 🐛 [Bug]: Jet, inside {{ embed() }} no error propagation
### Bug Description

https://github.com/gofiber/template/issues/339#issuecomment-1951440680

### How to Reproduce

https://github.com/iacore/debug-gofiber-jet-no-error

### Expected Behavior

show error pls

### Template package Version

see in repro repo

### Code Snippet (optional)

_No response_

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

### PR DESCRIPTION
**Pull request by iacore**
fixes #341

## Summary by CodeRabbit

- **Refactor**
	- Improved error handling in template rendering to enhance reliability.
- **Tests**
	- Added tests to ensure robust error handling when rendering templates with missing data.

### CODE REVIEW

**Comment by iacore** [comment]
nononononononono i want none of this coderabbit thing

**Comment by iacore** [comment]
@coderabbitai ignore

can we ban this thing from ever commenting on anywhere

**Review by ReneWerner87 — CHANGES_REQUESTED** [review]
Why is the error variable no longer used, what advantage do the numbered errors have if only one is used at a time? 

Can you please check for the error after the binding before executing the next action

**Comment by iacore** [comment]
> Why is the error variable no longer used, what advantage do the numbered errors have if only one is used at a time?
> 
> Can you please check for the error after the binding before executing the next action

which line?

**Comment by iacore** [comment]
nvm. good luck with your ai.

**Pull request closed without merging**
