### PR TITLE
Added Benchmarks for all engines

### PR DESCRIPTION
**Pull request by ytsruh**
Added benchmakrs to all engines (except Mustache extended). A summary & charts were added to the README file for future reference

This is a full PR that should hopefully satisfy #227

### CODE REVIEW

**Comment by efectn** [comment]
Can you add benchmark for slim engine

**Comment by efectn** [comment]
> Happy to add them, however all of slim_test.go file was commented out & the Slim engine wasn't mentioned in the docs. Do you know which implementation of slim is used and I can add them tonight?

Yeah it doesn't have docs and i've never used it before. Maybe we should try to uncomment tests and add benchmark. We will add README later

**Comment by ytsruh** [comment]
I'll give it a try and see how I get on (no promises though!)

**Comment by efectn** [comment]
> OK so I had look over this and I think I know why it was commented out, I dont think the implementation works as is expected - it seems to add additional div elements to layouts. See below: Screenshot 2023-04-19 at 17 54 59 On top of this the control flow from the Go implementation appears to not work, at least not using the syntax of the original engine. The two references I used are:
> 
> * https://github.com/mattn/go-slim
> * https://github.com/slim-template/slim
> 
> With all of this in mind, I'm not sure the currently able to add the Benchmark. If I did it wouldn't be particularly useful.
> 
> Would be ok if we split Slim engine benchmark to its own issue? And somebody can work on the implementation of the engine and then we can add the benchmark afterwards?

Ok, let's skip it for now

**Comment by ReneWerner87** [comment]
@ytsruh can you pls check the tests

**Review by efectn — COMMENTED** [review]
Don't forget to delete ds store

**Comment by ytsruh** [comment]
Hi guys, sorry about the delay in fixing the tests. All passing now.

**Comment by ReneWerner87** [comment]
will check it on sunday at the latest

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
maybe we should use 
https://github.com/marketplace/actions/continuous-benchmarking-for-go
for the benchmark visualisation

**Pull request merged**
