### PR TITLE
Add AddFuncMap to most Engines

### PR DESCRIPTION
**Pull request by cmd777**
Title, basically.

Only the HTML Engine has `AddFuncMap`, the rest of them only have `AddFunc`. This adds the `AddFuncMap` to most Engines:
- Ace
- Amber
- Django
- Handlebars
- Jet
- Pug
<sub>and slim</sub>

### CODE REVIEW

**Review by efectn — COMMENTED** [review]
Can you add tests like https://github.com/gofiber/template/blob/master/html/html_test.go#L88

**Comment by cmd777** [comment]
> Can you add tests like https://github.com/gofiber/template/blob/master/html/html_test.go#L88

Yup. Tests were added. Well.. except for slim.. as all the tests in it are commented out.
Also added the `FuncMap` func (to export all funcmaps) to _almost_ all engines. (again, except for slim, and mustache)

**Comment by efectn** [comment]
> > Can you add tests like https://github.com/gofiber/template/blob/master/html/html_test.go#L88
> 
> Yup. Tests were added. Well.. except for slim.. as all the tests in it are commented out. Also added the `FuncMap` func (to export all funcmaps) to _almost_ all engines. (again, except for slim, and mustache)

Slim has support for custom functions. You can add it -> https://github.com/gofiber/template/blob/master/slim/slim.go#L40

**Comment by cmd777** [comment]
> > > Can you add tests like https://github.com/gofiber/template/blob/master/html/html_test.go#L88
> > 
> > 
> > Yup. Tests were added. Well.. except for slim.. as all the tests in it are commented out. Also added the `FuncMap` func (to export all funcmaps) to _almost_ all engines. (again, except for slim, and mustache)
> 
> Slim has support for custom functions. You can add it -> https://github.com/gofiber/template/blob/master/slim/slim.go#L40

It does, but it's very broken

```go
func Test_AddFuncMap(t *testing.T) {
	dir, _ := os.MkdirTemp(".", "")
	defer os.RemoveAll(dir)

	_ = os.WriteFile(dir+"/func_map.slim", []byte(`h2 = lower(Var1)`), 0700)

	engine := New(dir, ".slim")

	fm := map[string]interface{}{
		"lower": func(s string) string {
			return strings.ToLower(s)
		},
		"upper": func(s string) string {
			return strings.ToUpper(s)
		},
	}

	engine.AddFuncMap(fm)

	if err := engine.Load(); err != nil {
		t.Fatalf("load: %v\n", err)
	}

	var buf bytes.Buffer
	engine.Render(&buf, "func_map", map[string]interface{}{
		"Var1": "LOwEr",
		"Var2": "upPEr",
	})
	expect := `<h2>lower</h2><p>UPPER</p>`
	result := trim(buf.String())
	if expect != result {
		t.Fatalf("Expected:\n%s\nResult:\n%s\n", expect, result)
	}

	fm2 := engine.FuncMap()
	if _, ok := fm2["lower"]; !ok {
		t.Fatalf("Function lower does not exist in FuncMap().\n")
	}
	if _, ok := fm2["upper"]; !ok {
		t.Fatalf("Function upper does not exist in FuncMap().\n")
	}
}

```

This fails with:
```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^Test_AddFuncMap$ github.com/gofiber/template/slim/v2

--- FAIL: Test_AddFuncMap (0.00s)
    /home/cmd777/Documents/template/slim/slim_test.go:151: Expected:
        <h2>lower</h2><p>UPPER</p>
        Result:
        <h2>
FAIL
FAIL	github.com/gofiber/template/slim/v2	0.004s
FAIL
```

And it's not the fault of the AddFuncMap, because if we just remove that fatal error

```go
func Test_AddFuncMap(t *testing.T) {
	dir, _ := os.MkdirTemp(".", "")
	defer os.RemoveAll(dir)

	_ = os.WriteFile(dir+"/func_map.slim", []byte(`h2 = lower(Var1)`), 0700)

	engine := New(dir, ".slim")

	fm := map[string]interface{}{
		"lower": func(s string) string {
			return strings.ToLower(s)
		},
		"upper": func(s string) string {
			return strings.ToUpper(s)
		},
	}

	engine.AddFuncMap(fm)

	if err := engine.Load(); err != nil {
		t.Fatalf("load: %v\n", err)
	}

	var buf bytes.Buffer
	engine.Render(&buf, "func_map", map[string]interface{}{
		"Var1": "LOwEr",
		"Var2": "upPEr",
	})

	fm2 := engine.FuncMap()
	if _, ok := fm2["lower"]; !ok {
		t.Fatalf("Function lower does not exist in FuncMap().\n")
	}
	if _, ok := fm2["upper"]; !ok {
		t.Fatalf("Function upper does not exist in FuncMap().\n")
	}
}
```

Then it succeeds:
```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^Test_AddFuncMap$ github.com/gofiber/template/slim/v2

ok  	github.com/gofiber/template/slim/v2	0.004s
```

And that's how the syntax should be, according to the original testdata

https://github.com/mattn/go-slim/blob/4a5a951e28160d3fdc4709941ef6744545e8a09e/testdata/test_func.slim#L7

**Comment by efectn** [comment]
> > > > Can you add tests like https://github.com/gofiber/template/blob/master/html/html_test.go#L88
> > > 
> > > 
> > > Yup. Tests were added. Well.. except for slim.. as all the tests in it are commented out. Also added the `FuncMap` func (to export all funcmaps) to _almost_ all engines. (again, except for slim, and mustache)
> > 
> > 
> > Slim has support for custom functions. You can add it -> https://github.com/gofiber/template/blob/master/slim/slim.go#L40
> 
> It does, but it's very broken
> 
> ```go
> func Test_AddFuncMap(t *testing.T) {
> 	dir, _ := os.MkdirTemp(".", "")
> 	defer os.RemoveAll(dir)
> 
> 	_ = os.WriteFile(dir+"/func_map.slim", []byte(`h2 = lower(Var1)`), 0700)
> 
> 	engine := New(dir, ".slim")
> 
> 	fm := map[string]interface{}{
> 		"lower": func(s string) string {
> 			return strings.ToLower(s)
> 		},
> 		"upper": func(s string) string {
> 			return strings.ToUpper(s)
> 		},
> 	}
> 
> 	engine.AddFuncMap(fm)
> 
> 	if err := engine.Load(); err != nil {
> 		t.Fatalf("load: %v\n", err)
> 	}
> 
> 	var buf bytes.Buffer
> 	engine.Render(&buf, "func_map", map[string]interface{}{
> 		"Var1": "LOwEr",
> 		"Var2": "upPEr",
> 	})
> 	expect := `<h2>lower</h2><p>UPPER</p>`
> 	result := trim(buf.String())
> 	if expect != result {
> 		t.Fatalf("Expected:\n%s\nResult:\n%s\n", expect, result)
> 	}
> 
> 	fm2 := engine.FuncMap()
> 	if _, ok := fm2["lower"]; !ok {
> 		t.Fatalf("Function lower does not exist in FuncMap().\n")
> 	}
> 	if _, ok := fm2["upper"]; !ok {
> 		t.Fatalf("Function upper does not exist in FuncMap().\n")
> 	}
> }
> ```
> 
> This fails with:
> 
> ```
> Running tool: /usr/local/go/bin/go test -timeout 30s -run ^Test_AddFuncMap$ github.com/gofiber/template/slim/v2
> 
> --- FAIL: Test_AddFuncMap (0.00s)
>     /home/cmd777/Documents/template/slim/slim_test.go:151: Expected:
>         <h2>lower</h2><p>UPPER</p>
>         Result:
>         <h2>
> FAIL
> FAIL	github.com/gofiber/template/slim/v2	0.004s
> FAIL
> ```
> 
> And it's not the fault of the AddFuncMap, because if we just remove that fatal error
> 
> ```go
> func Test_AddFuncMap(t *testing.T) {
> 	dir, _ := os.MkdirTemp(".", "")
> 	defer os.RemoveAll(dir)
> 
> 	_ = os.WriteFile(dir+"/func_map.slim", []byte(`h2 = lower(Var1)`), 0700)
> 
> 	engine := New(dir, ".slim")
> 
> 	fm := map[string]interface{}{
> 		"lower": func(s string) string {
> 			return strings.ToLower(s)
> 		},
> 		"upper": func(s string) string {
> 			return strings.ToUpper(s)
> 		},
> 	}
> 
> 	engine.AddFuncMap(fm)
> 
> 	if err := engine.Load(); err != nil {
> 		t.Fatalf("load: %v\n", err)
> 	}
> 
> 	var buf bytes.Buffer
> 	engine.Render(&buf, "func_map", map[string]interface{}{
> 		"Var1": "LOwEr",
> 		"Var2": "upPEr",
> 	})
> 
> 	fm2 := engine.FuncMap()
> 	if _, ok := fm2["lower"]; !ok {
> 		t.Fatalf("Function lower does not exist in FuncMap().\n")
> 	}
> 	if _, ok := fm2["upper"]; !ok {
> 		t.Fatalf("Function upper does not exist in FuncMap().\n")
> 	}
> }
> ```
> 
> Then it succeeds:
> 
> ```
> Running tool: /usr/local/go/bin/go test -timeout 30s -run ^Test_AddFuncMap$ github.com/gofiber/template/slim/v2
> 
> ok  	github.com/gofiber/template/slim/v2	0.004s
> ```
> 
> And that's how the syntax should be, according to the original testdata
> 
> https://github.com/mattn/go-slim/blob/4a5a951e28160d3fdc4709941ef6744545e8a09e/testdata/test_func.slim#L7

Ok will check it

**Comment by ReneWerner87** [comment]
@efectn do you see anything else that is missing ?

**Comment by efectn** [comment]
> @efectn do you see anything else that is missing ?

I couldn't yet take a look. I think we can check it after merging the PR

**Pull request merged**
