### PR TITLE
Only for triggering rebuild for Fiber v2.0.1

### PR DESCRIPTION
**Pull request by suntong**
Trigger rebuild for Fiber v2.0.1

### CODE REVIEW

**Comment by Fenny** [comment]
Tests passing :/

**Comment by suntong** [comment]
Strange. 

Then what's the problem of https://github.com/gofiber/fiber/issues/814 be? 
Can you duplicate it at your side @Fenny, as I have no idea what's wrong. 
Here is what had been changed:

https://github.com/suntong/fiber_demo/commit/8caf82751cf4b1406427b5b7f88b58d72b71ae9f#diff-1a1f2527a48227f98a3eea2f961aaa26

**Comment by Fenny** [comment]
@suntong <https://github.com/suntong/fiber_demo/blob/8caf82751cf4b1406427b5b7f88b58d72b71ae9f/template-html/main.go#L23>
```go
import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/compress"
)

// ..

app.Use(compress.New())
```

**Comment by suntong** [comment]
Oh, I remove compress from `main0.go`
https://github.com/suntong/fiber_demo/blob/master/template-html/main0.go

that's what I'm reporting with.

**Comment by Fenny** [comment]
By any chance, you could join me on our [Discord channel](https://gofiber.io/discord)?

**Comment by Fenny** [comment]
```go
engine := html.New("./views", ".html")
engine.Reload(true)
```
Seems to fix the problem, I made a PR to your repo https://github.com/suntong/fiber_demo/pull/1

**Pull request closed without merging**
